all:
  hosts:
    kibana_node:
      ansible_host: <ip>
      ansible_user: elk-master 
      ansible_password: el4stic
      ansible_become_pass: el4stic


  children:
    elk_nodes:
      hosts:
        node1:
          ansible_host: <ip> 
        node2:
          ansible_host: <ip>
      vars:
        ansible_user: elk-admin 
        ansible_password: el4stic
        ansible_become_pass: el4stic
      
