all:
  hosts:
    kibana_node:
      ansible_ssh_private_key_file: .vagrant/machines/kibana/virtualbox/private_key
      ansible_host: 10.0.2.6
      ansible_user: vagrant 
      ansible_become_pass: vagrant


  children:
    elk_nodes:
      hosts:
        node1:
          ansible_host: 10.0.2.4
          ansible_ssh_private_key_file: .vagrant/machines/node1/virtualbox/private_key

        node2:
          ansible_host: 10.0.2.5
          ansible_ssh_private_key_file: .vagrant/machines/node2/virtualbox/private_key

      vars:
        ansible_user: vagrant 
        ansible_become_pass: vagrant
