all:
  hosts:
    elk-master:
      ansible_host: 
      ansible_port: 10022
      ansible_user: bob
    

  children:
    elk_nodes:
      hosts:
        node1:
          ansible_host: 
        node2:
          ansible_host: 12223
      vars:
        ansible_host: 81.65.166.101
        ansible_user: bob
