- hosts: kibana_nodes
  become: yes

  vars:
    - kibana_server_port: 5601
    - kibana_server_host: "0.0.0.0"
    - kibana_elasticsearch_url: "http://192.168.2.2:9200"
    - kibana_elasticsearch_username: ""
    - kibana_elasticsearch_password: ""

  tasks:
    - name: Install apt requirements
      apt:
        name: 
          - apt-transport-https
          - uuid-runtime
          - openjdk-11-jre-headless
          - gpg
        state: present
        update_cache: yes

    - name: Add elasticsearch repo GPG key
      apt_key:
        url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
        state: present

    - name: Add elasticsearch apt repo
      apt_repository:
        repo: "deb https://artifacts.elastic.co/packages/7.x/apt stable main"
        state: present

    - name: Install Kibana
      apt: 
        name: kibana
        state: present

    - name: Configure Kibana.
      template:
        src: kibana.yml.j2 
        dest: /etc/kibana/kibana.yml
        owner: root
        group: kibana
        mode: 0740 # Kibana service run with user kibana in group kibana
      notify: restart kibana

    - name: Create kibana log file
      file:
        state: touch
        path: /var/log/kibana.log
        owner: kibana
        mode: 740

    - name: Start Kibana.
      systemd:
        name: kibana
        state: started
        enabled: yes
        daemon_reload: yes #required before first run


    - name: Make sure Kibana is running before proceeding.
      wait_for:
        host: "{{ ansible_host }}"
        port: "{{ kibana_server_port }}"
        timeout: 600
    

  handlers:
    - name: restart kibana
      service:
        name: kibana
        state: restarted