---
- hosts: <group>
  become: yes

  tasks:
    - name: upgrade system
      command: apt upgrade -y
    
    - name: Install apt requirements
      apt:
        name: 
          - apt-transport-https
          - uuid-runtime
          - openjdk-11-jre-headless
          - gpg
        state: present
        update_cache: yes