---
- hosts: <group_elastic_nodes>
  become: yes #tasks will run as root by default

  tasks:
    - name: update apt cache
      command: apt update
    
    - name: upgrade system
      command: apt upgrade -y
    
    - name: Install apt requirements
      apt:
        name: 
          - apt-transport-https
          - uuid-runtime
          - openjdk-11-jre-headless
          - gpg
        update_cache: yes